### ISSUE TITLE
issue with table renaming handling

### ISSUE THREAD

**Issue by chrisvidal** [dead23angel/octovisit#4]
if you want to rename the table in the initial migration, you need to handle as well the renaming of the previous table the plugin was created, which was `cwteam_octovisit_visits`. Now the plugin is not working at all on my side because your new table name has not been created because of the upgrade process.

**Comment by dead23angel** [comment]
> if you want to rename the table in the initial migration, you need to handle as well the renaming of the previous table the plugin was created, which was `cwteam_octovisit_visits`. Now the plugin is not working at all on my side because your new table name has not been created because of the upgrade process.

Reinstall plugin please or rename table manual in your database

**Comment by chrisvidal** [comment]
I can't reinstall, I already have visit data in the table :(
I renamed it manually.
thanks
