### ISSUE TITLE
issue with displaying the stats

### ISSUE THREAD

**Issue by chrisvidal** [dead23angel/octovisit#5]
in a form partial i am trying to display the user name who visited my model and i have an exception

code
```
<ul>
    <?php foreach ($model->visits as $visit): ?>
        <li class="oc-icon-file-o">visit
            <?= e($visit->present()->user->name) ?>
        </li>
    <?php endforeach ?>
</ul>
```

error:
```
Undefined array key "user_id"
~/plugins/cwteam/octovisit/presenters/VisitPresenter.php line 28
```

* Get the associated User from the model instance
     *
     * @return Model
     */
    public function user(): Model
    {
        $userId = $this->model->data['user_id'];
        $userNamespace = config('dead23angel.octovisit::octovisit.user_namespace');
...

```

**Comment by dead23angel** [comment]
@chrisvidal 

Use v1.0.4 and take a close look at the documentation. In order to keep in touch with the user, it is necessary to use the method `->withUser() `

**Comment by chrisvidal** [comment]
i'm sorry, the documentaion is confusing:

examples uses `visits` and the table talks about using `visit()`

`$post->visits->first()->present()->ip`

or 
`$post->visits->first()->present()->user->name`

**Comment by chrisvidal** [comment]
and bascially i dont find any way to use this. 
using visits or visit all leads to errors.
can you insert real example that works in the documentation please on top of the api table?
that would be helpful i think

**Comment by dead23angel** [comment]
@chrisvidal 

I published the v1.0.5 release, fixed a bug in the presenter and updated the readme

**Comment by dead23angel** [comment]
> and bascially i dont find any way to use this. using visits or visit all leads to errors. can you insert real example that works in the documentation please on top of the api table? that would be helpful i think

https://github.com/dead23angel/octovisit?tab=readme-ov-file#view-list-visitors-in-form-backend

**Comment by chrisvidal** [comment]
thanks @dead23angel 
the example is missing some information with regards to the `View list visitors in form Backend`
the point 1 is obviously a copy/paste from the previous poiunt which is not working in that case.

also, I still got the error 

```
Undefined array key "user_id"
~/plugins/cwteam/octovisit/presenters/VisitPresenter.php line 28
```

**Comment by dead23angel** [comment]
@chrisvidal 

Thanks, I fixed the readme. By mistake, make sure you are using version 1.0.5

**Comment by dead23angel** [comment]
I replace `$userId = $this->model->data['user_id'];` to `$userId = Arr::get($this->model->data, 'user_id');`. There should be no mistake

**Comment by chrisvidal** [comment]
thanks it works now
